FROM --platform=linux/amd64 golang:1.20.1-bullseye@sha256:87734b78d26a52260f303cf1b40df45b0797f972bd0250e56937c42114bf472c
LABEL maintainer="Fleet Developers"

RUN apt-get update && apt-get install -y \
	gcc \
	libgtk-3-dev \
	libayatana-appindicator3-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/fleet
RUN mkdir -p /output

WORKDIR /usr/src/fleet

COPY orbit ./orbit
COPY server ./server
COPY ee ./ee
COPY pkg ./pkg
COPY go.mod go.sum ./

CMD /bin/bash
